/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    _CSB_wire_177088027_0: THREE.Mesh
    Base_CSR2_Base_0: THREE.Mesh
    CaliperLF_CSR2_Calliper_Color_0: THREE.Mesh
    CaliperLF_CSR2_CalliperBadge_0: THREE.Mesh
    CaliperLF_CSR2_CalliperZone_0: THREE.Mesh
    CaliperLR_CSR2_Calliper_Color_0: THREE.Mesh
    CaliperLR_CSR2_CalliperBadge_0: THREE.Mesh
    CaliperLR_CSR2_CalliperZone_0: THREE.Mesh
    CaliperRF_CSR2_Calliper_Color_0: THREE.Mesh
    CaliperRF_CSR2_CalliperBadge_0: THREE.Mesh
    CaliperRF_CSR2_CalliperZone_0: THREE.Mesh
    CaliperRR_CSR2_Calliper_Color_0: THREE.Mesh
    CaliperRR_CSR2_CalliperBadge_0: THREE.Mesh
    CaliperRR_CSR2_CalliperZone_0: THREE.Mesh
    Carbon1_CSR2_Carbon1_0: THREE.Mesh
    Coloured_CSR2_Coloured_0: THREE.Mesh
    Coloured_Mirrors_0: THREE.Mesh
    DoorLF_Carbon1_CSR2_Carbon1_0: THREE.Mesh
    DoorLF_Coloured_CSR2_Coloured_0: THREE.Mesh
    DoorLF_Coloured_Mirrors_0: THREE.Mesh
    DoorLF_Glass_GlassClear_0: THREE.Mesh
    DoorLF_Glass_Window_0: THREE.Mesh
    DoorLF_Interior_CSR2_Interior_0: THREE.Mesh
    DoorLF_InteriorEmissive_CSR2_Interior_0: THREE.Mesh
    DoorLF_InteriorZone2_CSR2_InteriorZone2A_0: THREE.Mesh
    DoorLF_Light_CSR2_Light_0: THREE.Mesh
    DoorLF_Window_Glass_Material003_0: THREE.Mesh
    DoorRF_Carbon1_CSR2_Carbon1_0: THREE.Mesh
    DoorRF_Coloured_CSR2_Coloured_0: THREE.Mesh
    DoorRF_Coloured_Mirrors_0: THREE.Mesh
    DoorRF_Glass_GlassClear_0: THREE.Mesh
    DoorRF_Glass_Window_0: THREE.Mesh
    DoorRF_Interior_CSR2_Interior_0: THREE.Mesh
    DoorRF_InteriorEmissive_CSR2_Interior_0: THREE.Mesh
    DoorRF_InteriorZone2_CSR2_InteriorZone2A_0: THREE.Mesh
    DoorRF_Light_CSR2_Light_0: THREE.Mesh
    DoorRF_Window_Glass_Window_0: THREE.Mesh
    Glass_GlassClear_0: THREE.Mesh
    Glass_GlassRed_0: THREE.Mesh
    Glass_Material002_0: THREE.Mesh
    Grille1_CSR2_Grille1_0: THREE.Mesh
    Grille2_CSR2_Grille2_0: THREE.Mesh
    Grille3_CSR2_Grille3_0: THREE.Mesh
    Interior_CSR2_Interior_0: THREE.Mesh
    Interior_miter_0: THREE.Mesh
    InteriorEmissive_bottons_0: THREE.Mesh
    InteriorEmissive_miter_0: THREE.Mesh
    InteriorZone2_CSR2_InteriorZone2_0: THREE.Mesh
    InteriorZone2_CSR2_InteriorZone2A_0: THREE.Mesh
    Light001_brake_light_0: THREE.Mesh
    Light001_brake_park_light_0: THREE.Mesh
    Light001_CSR2_Light_0: THREE.Mesh
    Light001_headlight_0: THREE.Mesh
    Light001_Park_light_0: THREE.Mesh
    Paint_CSR2_CarPaint_0: THREE.Mesh
    SeatBelt_CSR2_Coloured_0: THREE.Mesh
    Spoiler_Hinge1_Coloured_CSR2_Coloured_0: THREE.Mesh
    Spoiler_Hinge2_Carbon1_CSR2_Carbon1_0: THREE.Mesh
    Spoiler_Hinge2_Coloured_CSR2_Coloured_0: THREE.Mesh
    Spoiler_Hinge2_Paint_CSR2_CarPaint_0: THREE.Mesh
    Spoiler_Hinge3_Coloured_CSR2_Coloured_0: THREE.Mesh
    SteeringWheel_Carbon1_CSR2_Carbon1_0: THREE.Mesh
    SteeringWheel_Interior_CSR2_Interior_0: THREE.Mesh
    SteeringWheel_InteriorEmissive_bottons_0: THREE.Mesh
    SteeringWheel_InteriorEmissive_CSR2_Interior_0: THREE.Mesh
    SteeringWheel_InteriorEmissive_miter_0: THREE.Mesh
    Trunk_Carbon1_CSR2_Carbon1_0: THREE.Mesh
    Trunk_Coloured_CSR2_Coloured_0: THREE.Mesh
    Trunk_Paint_CSR2_CarPaint_0: THREE.Mesh
    Wheel_01_LF_CSR2_Wheel1A_Rim_0: THREE.Mesh
    Wheel_01_LF_CSR2_Wheel1A_Rotor_0: THREE.Mesh
    Wheel_01_LF_CSR2_Wheel1A_Tire_0: THREE.Mesh
    Wheel_01_LR_CSR2_Wheel1A_Rim_0: THREE.Mesh
    Wheel_01_LR_CSR2_Wheel1A_Rotor_0: THREE.Mesh
    Wheel_01_LR_CSR2_Wheel1A_Tire_0: THREE.Mesh
    Wheel_01_RF_CSR2_Wheel1A_Rim_0: THREE.Mesh
    Wheel_01_RF_CSR2_Wheel1A_Rotor_0: THREE.Mesh
    Wheel_01_RF_CSR2_Wheel1A_Tire_0: THREE.Mesh
    Wheel_01_RR_CSR2_Wheel1A_Rim_0: THREE.Mesh
    Wheel_01_RR_CSR2_Wheel1A_Rotor_0: THREE.Mesh
    Wheel_01_RR_CSR2_Wheel1A_Tire_0: THREE.Mesh
  }
  materials: {
    wire_177088027: THREE.MeshStandardMaterial
    CSR2_Base: THREE.MeshStandardMaterial
    CSR2_Calliper_Color: THREE.MeshStandardMaterial
    CSR2_CalliperBadge: THREE.MeshStandardMaterial
    CSR2_CalliperZone: THREE.MeshStandardMaterial
    CSR2_Carbon1: THREE.MeshStandardMaterial
    CSR2_Coloured: THREE.MeshPhysicalMaterial
    Mirrors: THREE.MeshStandardMaterial
    GlassClear: THREE.MeshStandardMaterial
    Window: THREE.MeshPhysicalMaterial
    CSR2_Interior: THREE.MeshPhysicalMaterial
    CSR2_InteriorZone2A: THREE.MeshStandardMaterial
    CSR2_Light: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshPhysicalMaterial
    GlassRed: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    CSR2_Grille1: THREE.MeshStandardMaterial
    CSR2_Grille2: THREE.MeshStandardMaterial
    CSR2_Grille3: THREE.MeshStandardMaterial
    miter: THREE.MeshStandardMaterial
    bottons: THREE.MeshStandardMaterial
    CSR2_InteriorZone2: THREE.MeshStandardMaterial
    brake_light: THREE.MeshStandardMaterial
    brake_park_light: THREE.MeshStandardMaterial
    headlight: THREE.MeshStandardMaterial
    Park_light: THREE.MeshStandardMaterial
    CSR2_CarPaint: THREE.MeshStandardMaterial
    CSR2_Wheel1A_Rim: THREE.MeshStandardMaterial
    CSR2_Wheel1A_Rotor: THREE.MeshStandardMaterial
    CSR2_Wheel1A_Tire: THREE.MeshPhysicalMaterial
  }
}

export function Chiron(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/chiron6.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.073, -2.181, -0.079]} rotation={[-Math.PI / 2, 0, 0]} scale={2.87}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 50.054, 150.068]} rotation={[Math.PI / 2, 0, 0]} scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CaliperLF_CSR2_Calliper_Color_0.geometry}
              material={materials.CSR2_Calliper_Color}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CaliperLF_CSR2_CalliperBadge_0.geometry}
              material={materials.CSR2_CalliperBadge}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CaliperLF_CSR2_CalliperZone_0.geometry}
              material={materials.CSR2_CalliperZone}
            />
          </group>
          <group position={[0, 55.636, -201.437]} rotation={[Math.PI / 2, 0, 0]} scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CaliperLR_CSR2_Calliper_Color_0.geometry}
              material={materials.CSR2_Calliper_Color}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CaliperLR_CSR2_CalliperBadge_0.geometry}
              material={materials.CSR2_CalliperBadge}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CaliperLR_CSR2_CalliperZone_0.geometry}
              material={materials.CSR2_CalliperZone}
            />
          </group>
          <group
            position={[-132.902, 50.054, 150.068]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CaliperRF_CSR2_Calliper_Color_0.geometry}
              material={materials.CSR2_Calliper_Color}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CaliperRF_CSR2_CalliperBadge_0.geometry}
              material={materials.CSR2_CalliperBadge}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CaliperRF_CSR2_CalliperZone_0.geometry}
              material={materials.CSR2_CalliperZone}
            />
          </group>
          <group
            position={[-130.053, 55.636, -201.436]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CaliperRR_CSR2_Calliper_Color_0.geometry}
              material={materials.CSR2_Calliper_Color}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CaliperRR_CSR2_CalliperBadge_0.geometry}
              material={materials.CSR2_CalliperBadge}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CaliperRR_CSR2_CalliperZone_0.geometry}
              material={materials.CSR2_CalliperZone}
            />
          </group>
          <group position={[-2.182, 85.73, -92.938]} rotation={[Math.PI / 2, 0, 0]} scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Coloured_CSR2_Coloured_0.geometry}
              material={materials.CSR2_Coloured}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Coloured_Mirrors_0.geometry}
              material={materials.Mirrors}
            />
          </group>
          <group position={[124.471, 82.185, 40.629]} rotation={[Math.PI / 2, 0, 0]} scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.DoorLF_Coloured_CSR2_Coloured_0.geometry}
              material={materials.CSR2_Coloured}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.DoorLF_Coloured_Mirrors_0.geometry}
              material={materials.Mirrors}
            />
          </group>
          <group position={[142.971, 122.574, 74.04]} rotation={[Math.PI / 2, 0, 0]} scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.DoorLF_Glass_GlassClear_0.geometry}
              material={materials.GlassClear}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.DoorLF_Glass_Window_0.geometry}
              material={materials.Window}
            />
          </group>
          <group position={[-124.419, 82.823, 40.989]} rotation={[Math.PI / 2, 0, 0]} scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.DoorRF_Coloured_CSR2_Coloured_0.geometry}
              material={materials.CSR2_Coloured}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.DoorRF_Coloured_Mirrors_0.geometry}
              material={materials.Mirrors}
            />
          </group>
          <group position={[-142.971, 122.574, 74.04]} rotation={[Math.PI / 2, 0, 0]} scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.DoorRF_Glass_GlassClear_0.geometry}
              material={materials.GlassClear}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.DoorRF_Glass_Window_0.geometry}
              material={materials.Window}
            />
          </group>
          <group position={[-0.782, 95.647, -58.065]} rotation={[Math.PI / 2, 0, 0]} scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Glass_GlassClear_0.geometry}
              material={materials.GlassClear}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Glass_GlassRed_0.geometry}
              material={materials.GlassRed}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Glass_Material002_0.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group position={[7.92, 91.901, 48.1]} rotation={[Math.PI / 2, 0, 0]} scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interior_CSR2_Interior_0.geometry}
              material={materials.CSR2_Interior}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interior_miter_0.geometry}
              material={materials.miter}
            />
          </group>
          <group position={[34.733, 94.581, 81.625]} rotation={[Math.PI / 2, 0, 0]} scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.InteriorEmissive_bottons_0.geometry}
              material={materials.bottons}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.InteriorEmissive_miter_0.geometry}
              material={materials.miter}
            />
          </group>
          <group position={[-1.259, 98.214, -5.93]} rotation={[Math.PI / 2, 0, 0]} scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.InteriorZone2_CSR2_InteriorZone2_0.geometry}
              material={materials.CSR2_InteriorZone2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.InteriorZone2_CSR2_InteriorZone2A_0.geometry}
              material={materials.CSR2_InteriorZone2A}
            />
          </group>
          <group position={[-0.15, 84.911, 95.152]} rotation={[Math.PI / 2, 0, 0]} scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Light001_brake_light_0.geometry}
              material={materials.brake_light}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Light001_brake_park_light_0.geometry}
              material={materials.brake_park_light}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Light001_CSR2_Light_0.geometry}
              material={materials.CSR2_Light}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Light001_headlight_0.geometry}
              material={materials.headlight}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Light001_Park_light_0.geometry}
              material={materials.Park_light}
            />
          </group>
          <group position={[56.151, 104.503, 61.339]} rotation={[Math.PI / 2, 0, 0]} scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SteeringWheel_InteriorEmissive_bottons_0.geometry}
              material={materials.bottons}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SteeringWheel_InteriorEmissive_CSR2_Interior_0.geometry}
              material={materials.CSR2_Interior}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SteeringWheel_InteriorEmissive_miter_0.geometry}
              material={materials.miter}
            />
          </group>
          <group position={[138.458, 47.929, 176.988]} rotation={[Math.PI / 2, 0, 0]} scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wheel_01_LF_CSR2_Wheel1A_Rim_0.geometry}
              material={materials.CSR2_Wheel1A_Rim}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wheel_01_LF_CSR2_Wheel1A_Rotor_0.geometry}
              material={materials.CSR2_Wheel1A_Rotor}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wheel_01_LF_CSR2_Wheel1A_Tire_0.geometry}
              material={materials.CSR2_Wheel1A_Tire}
            />
          </group>
          <group
            position={[136.202, 51.226, -215.993]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wheel_01_LR_CSR2_Wheel1A_Rim_0.geometry}
              material={materials.CSR2_Wheel1A_Rim}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wheel_01_LR_CSR2_Wheel1A_Rotor_0.geometry}
              material={materials.CSR2_Wheel1A_Rotor}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wheel_01_LR_CSR2_Wheel1A_Tire_0.geometry}
              material={materials.CSR2_Wheel1A_Tire}
            />
          </group>
          <group position={[-138.458, 47.929, 176.18]} rotation={[Math.PI / 2, 0, 0]} scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wheel_01_RF_CSR2_Wheel1A_Rim_0.geometry}
              material={materials.CSR2_Wheel1A_Rim}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wheel_01_RF_CSR2_Wheel1A_Rotor_0.geometry}
              material={materials.CSR2_Wheel1A_Rotor}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wheel_01_RF_CSR2_Wheel1A_Tire_0.geometry}
              material={materials.CSR2_Wheel1A_Tire}
            />
          </group>
          <group
            position={[-136.202, 51.226, -213.412]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wheel_01_RR_CSR2_Wheel1A_Rim_0.geometry}
              material={materials.CSR2_Wheel1A_Rim}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wheel_01_RR_CSR2_Wheel1A_Rotor_0.geometry}
              material={materials.CSR2_Wheel1A_Rotor}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wheel_01_RR_CSR2_Wheel1A_Tire_0.geometry}
              material={materials.CSR2_Wheel1A_Tire}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes._CSB_wire_177088027_0.geometry}
            material={materials.wire_177088027}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base_CSR2_Base_0.geometry}
            material={materials.CSR2_Base}
            position={[-0.444, 57.763, 76.447]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Carbon1_CSR2_Carbon1_0.geometry}
            material={materials.CSR2_Carbon1}
            position={[3.205, 86.517, -8.046]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorLF_Carbon1_CSR2_Carbon1_0.geometry}
            material={materials.CSR2_Carbon1}
            position={[127.274, 91.783, 29.147]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorLF_Interior_CSR2_Interior_0.geometry}
            material={materials.CSR2_Interior}
            position={[106.685, 85.899, 51.186]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorLF_InteriorEmissive_CSR2_Interior_0.geometry}
            material={materials.CSR2_Interior}
            position={[105.162, 89.746, 64.081]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorLF_InteriorZone2_CSR2_InteriorZone2A_0.geometry}
            material={materials.CSR2_InteriorZone2A}
            position={[104.182, 89.766, 26.143]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorLF_Light_CSR2_Light_0.geometry}
            material={materials.CSR2_Light}
            position={[152.48, 121.133, 74.1]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorLF_Window_Glass_Material003_0.geometry}
            material={materials['Material.003']}
            position={[103.386, 136.794, -14.138]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorRF_Carbon1_CSR2_Carbon1_0.geometry}
            material={materials.CSR2_Carbon1}
            position={[-127.274, 91.783, 29.147]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorRF_Interior_CSR2_Interior_0.geometry}
            material={materials.CSR2_Interior}
            position={[-106.509, 87.674, 51.655]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorRF_InteriorEmissive_CSR2_Interior_0.geometry}
            material={materials.CSR2_Interior}
            position={[-109.72, 71.95, 41.629]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorRF_InteriorZone2_CSR2_InteriorZone2A_0.geometry}
            material={materials.CSR2_InteriorZone2A}
            position={[-104.182, 89.766, 26.143]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorRF_Light_CSR2_Light_0.geometry}
            material={materials.CSR2_Light}
            position={[-152.48, 121.133, 74.1]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorRF_Window_Glass_Window_0.geometry}
            material={materials.Window}
            position={[-101.065, 139.805, -19.346]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Grille1_CSR2_Grille1_0.geometry}
            material={materials.CSR2_Grille1}
            position={[-1.542, 65.994, -53.064]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Grille2_CSR2_Grille2_0.geometry}
            material={materials.CSR2_Grille2}
            position={[0.116, 50.317, 186.952]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Grille3_CSR2_Grille3_0.geometry}
            material={materials.CSR2_Grille3}
            position={[0, 106.84, -109.583]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Paint_CSR2_CarPaint_0.geometry}
            material={materials.CSR2_CarPaint}
            position={[0.311, 140.831, -144.219]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SeatBelt_CSR2_Coloured_0.geometry}
            material={materials.CSR2_Coloured}
            position={[93.568, 97.34, -46.004]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Spoiler_Hinge1_Coloured_CSR2_Coloured_0.geometry}
            material={materials.CSR2_Coloured}
            position={[0, 103.879, -289.253]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Spoiler_Hinge2_Carbon1_CSR2_Carbon1_0.geometry}
            material={materials.CSR2_Carbon1}
            position={[0, 117.486, -299.601]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Spoiler_Hinge2_Coloured_CSR2_Coloured_0.geometry}
            material={materials.CSR2_Coloured}
            position={[-0.294, 115.103, -296.017]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Spoiler_Hinge2_Paint_CSR2_CarPaint_0.geometry}
            material={materials.CSR2_CarPaint}
            position={[0, 117.667, -306.87]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Spoiler_Hinge3_Coloured_CSR2_Coloured_0.geometry}
            material={materials.CSR2_Coloured}
            position={[0, 106.388, -295.441]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SteeringWheel_Carbon1_CSR2_Carbon1_0.geometry}
            material={materials.CSR2_Carbon1}
            position={[56.298, 99.664, 71.854]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SteeringWheel_Interior_CSR2_Interior_0.geometry}
            material={materials.CSR2_Interior}
            position={[56.265, 102.04, 61.455]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Trunk_Carbon1_CSR2_Carbon1_0.geometry}
            material={materials.CSR2_Carbon1}
            position={[0, 98.927, 238.56]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Trunk_Coloured_CSR2_Coloured_0.geometry}
            material={materials.CSR2_Coloured}
            position={[0.192, 96.535, 220.146]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Trunk_Paint_CSR2_CarPaint_0.geometry}
            material={materials.CSR2_CarPaint}
            position={[0, 100.278, 243.48]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.144}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/chiron6.glb')
